server:
  applicationConnectors:
  - type: http 
  adminConnectors:
  - type: http
logging:
  level: INFO
  loggers:
    org.metadatacenter: DEBUG
    org.metadatacenter.server.neo4j.proxy.AbstractNeo4JProxy: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      currentLogFilename: ${CEDAR_HOME}/log/cedar-template-server/dropwizard.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: ${CEDAR_HOME}/log/cedar-template-server/dropwizard-%d.log
      archivedFileCount: 30
      timeZone: UTC
