package org.metadatacenter.cedar.template.resources;

import javax.management.InstanceNotFoundException;
import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.UriInfo;
import java.rmi.AccessException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Path("/templates")
@Produces(MediaType.APPLICATION_JSON)
public class TemplatesResource {

  private
  @Context
  UriInfo uriInfo;

  private
  @Context
  HttpServletRequest request;

  public TemplatesResource() {
  }


  public static Result createTemplate(F.Option<Boolean> importMode) {
    try {
      AuthRequest authRequest = CedarAuthFromRequestFactory.fromRequest(request());
      Authorization.getUserAndEnsurePermission(authRequest, CedarPermission
          .TEMPLATE_CREATE);

      JsonNode template = request().body().asJson();
      if (template == null) {
        Logger.error("Expecting Json data");
        return badRequest("Expecting Json data");
      }

      ProvenanceInfo pi = ProvenanceUtil.build(cedarConfig, authRequest);
      checkImportModeSetProvenanceAndId(CedarNodeType.TEMPLATE, template, pi, importMode);

      templateFieldService.saveNewFieldsAndReplaceIds(template, pi,
          cedarConfig.getLinkedDataPrefix(CedarNodeType.FIELD));
      JsonNode createdTemplate = templateService.createTemplate(template);
      MongoUtils.removeIdField(createdTemplate);

      // Set Location header pointing to the newly created template
      String id = createdTemplate.get("@id").asText();
      String absoluteUrl = routes.TemplateServerController.findTemplate(id).absoluteURL(request());

      response().setHeader(HttpConstants.HTTP_HEADER_LOCATION, absoluteUrl);
      // Return created response
      return created(createdTemplate);
    } catch (IllegalArgumentException e) {
      Logger.error("Illegal Argument while creating the template", e);
      return badRequestWithError(e);
    } catch (CedarUserNotFoundException e) {
      Logger.error("User not found", e);
      return unauthorizedWithError(e);
    } catch (AccessException e) {
      Logger.error("Access Error while creating the template", e);
      return forbiddenWithError(e);
    } catch (AuthorizationTypeNotFoundException e) {
      Logger.error("Authorization header not found", e);
      return badRequestWithError(e);
    } catch (Exception e) {
      Logger.error("Error while creating the template", e);
      return internalServerErrorWithError(e);
    }
  }

  public static Result findTemplate(String templateId) {
    try {
      Authorization.getUserAndEnsurePermission(CedarAuthFromRequestFactory.fromRequest(request()), CedarPermission
          .TEMPLATE_READ);
      JsonNode template = templateService.findTemplate(templateId);
      if (template != null) {
        // Remove autogenerated _id field to avoid exposing it
        MongoUtils.removeIdField(template);
        return ok(template);
      }
      Logger.error("Template not found:(" + templateId + ")");
      return notFound();
    } catch (IllegalArgumentException e) {
      Logger.error("Illegal Argument while reading the template", e);
      return badRequestWithError(e);
    } catch (CedarUserNotFoundException e) {
      Logger.error("User not found", e);
      return unauthorizedWithError(e);
    } catch (AccessException e) {
      Logger.error("Access Error while reading the template", e);
      return forbiddenWithError(e);
    } catch (AuthorizationTypeNotFoundException e) {
      Logger.error("Authorization header not found", e);
      return badRequestWithError(e);
    } catch (Exception e) {
      Logger.error("Error while reading the template", e);
      return internalServerErrorWithError(e);
    }
  }

  public static Result findAllTemplates(Integer limit, Integer offset, boolean summary, String fieldNames) {
    try {
      Authorization.getUserAndEnsurePermission(CedarAuthFromRequestFactory.fromRequest(request()), CedarPermission
          .TEMPLATE_READ);
      limit = ensureLimit(limit);
      checkPagingParameters(limit, offset);
      List<String> fieldNameList = getAndCheckFieldNames(fieldNames, summary);
      Map<String, Object> r = new HashMap<>();
      List<JsonNode> templates = null;
      if (summary) {
        templates = templateService.findAllTemplates(limit, offset, FIELD_NAMES_SUMMARY_LIST, FieldNameInEx.INCLUDE);
      } else if (fieldNameList != null) {
        templates = templateService.findAllTemplates(limit, offset, fieldNameList, FieldNameInEx.INCLUDE);
      } else {
        templates = templateService.findAllTemplates(limit, offset, FIELD_NAMES_EXCLUSION_LIST, FieldNameInEx.EXCLUDE);
      }
      long total = templateService.count();
      response().setHeader(CustomHttpConstants.HEADER_TOTAL_COUNT, String.valueOf(total));
      checkPagingParametersAgainstTotal(offset, total);
      String absoluteUrl = routes.TemplateServerController.findAllTemplates(0, 0, false, null).absoluteURL(request());
      absoluteUrl = UrlUtil.trimUrlParameters(absoluteUrl);
      String linkHeader = LinkHeaderUtil.getPagingLinkHeader(absoluteUrl, total, limit, offset);
      if (!linkHeader.isEmpty()) {
        response().setHeader(HttpConstants.HTTP_HEADER_LINK, linkHeader);
      }
      return ok(Json.toJson(templates));
    } catch (AccessException e) {
      Logger.error("Access Error while reading the templates", e);
      return forbiddenWithError(e);
    } catch (Exception e) {
      Logger.error("Error while reading the templates", e);
      return internalServerErrorWithError(e);
    }
  }

  public static Result updateTemplate(String templateId) {
    try {
      AuthRequest authRequest = CedarAuthFromRequestFactory.fromRequest(request());
      Authorization.getUserAndEnsurePermission(authRequest, CedarPermission.TEMPLATE_UPDATE);
      JsonNode newTemplate = request().body().asJson();
      ProvenanceInfo pi = ProvenanceUtil.build(cedarConfig, authRequest);
      ProvenanceUtil.patchProvenanceInfo(newTemplate, pi);
      templateFieldService.saveNewFieldsAndReplaceIds(newTemplate, pi,
          cedarConfig.getLinkedDataPrefix(CedarNodeType.FIELD));
      JsonNode updatedTemplate = templateService.updateTemplate(templateId, newTemplate);
      // Remove autogenerated _id field to avoid exposing it
      MongoUtils.removeIdField(updatedTemplate);
      return ok(updatedTemplate);
    } catch (IllegalArgumentException e) {
      Logger.error("Illegal Argument while reading the template", e);
      return badRequestWithError(e);
    } catch (InstanceNotFoundException e) {
      Logger.error("Template not found for update:(" + templateId + ")");
      return notFound();
    } catch (AccessException e) {
      Logger.error("Access Error while reading the template", e);
      return forbiddenWithError(e);
    } catch (Exception e) {
      Logger.error("Error while updating the template", e);
      return internalServerErrorWithError(e);
    }
  }

  public static Result deleteTemplate(String templateId) {
    try {
      Authorization.getUserAndEnsurePermission(CedarAuthFromRequestFactory.fromRequest(request()), CedarPermission
          .TEMPLATE_DELETE);
      templateService.deleteTemplate(templateId);
      return noContent();
    } catch (IllegalArgumentException e) {
      Logger.error("Illegal Argument while deleting the template", e);
      return badRequestWithError(e);
    } catch (InstanceNotFoundException e) {
      Logger.error("Template not found while deleting:(" + templateId + ")");
      return notFound();
    } catch (AccessException e) {
      Logger.error("Access Error while deleting the template", e);
      return forbiddenWithError(e);
    } catch (Exception e) {
      Logger.error("Error while deleting the template", e);
      return internalServerErrorWithError(e);
    }
  }

}