package org.metadatacenter.cedar.artifact.resources.rest;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.client.Invocation;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.metadatacenter.constant.LinkedData;
import org.metadatacenter.http.CedarResponseStatus;
import org.metadatacenter.model.CedarResourceType;
import org.metadatacenter.util.json.JsonMapper;

import java.io.IOException;

import static jakarta.ws.rs.core.HttpHeaders.AUTHORIZATION;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.metadatacenter.model.CedarResourceType.ELEMENT;
import static org.metadatacenter.model.CedarResourceType.FIELD;
import static org.metadatacenter.model.CedarResourceType.TEMPLATE;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_DESCRIPTION;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_TITLE;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_NAME;

/**
 * The stored JSON Schema title and description follow schema:name on every write. The title is the
 * canonical one whatever the client sent, the description keeps the client's "generated by" signature,
 * and an unsigned artifact reads the same whether it arrived as JSON or as YAML.
 */
public class DerivedTitleAndDescriptionTest extends AbstractRestTest {

  private static final String APPLICATION_YAML = "application/yaml";
  private static final String NAME = "NIAID Blueprint Compliant Schema 0.7.0";
  private static final String STALE_TITLE = "Niaid blueprint compliant schema 0.5.3 template schema";
  private static final String EDITOR = "generated by the CEDAR Template Editor 2.9.5";
  private static final String LIBRARY = "generated by the CEDAR Artifact Library";
  /** What the minimal fixtures sign their description with. */
  private static final String FIXTURE_EDITOR = "generated by the CEDAR Template Editor 2.1.11";

  @ParameterizedTest
  @EnumSource(value = CedarResourceType.class, names = {"TEMPLATE", "ELEMENT"})
  public void postReplacesThePairTheClientSent(CedarResourceType type) throws IOException {
    ObjectNode payload = minimalPayload(type);
    payload.put(SCHEMA_ORG_NAME, NAME);
    payload.put(JSON_SCHEMA_TITLE, STALE_TITLE);
    payload.put(JSON_SCHEMA_DESCRIPTION, STALE_TITLE + " " + EDITOR);

    JsonNode created = create(type, Entity.json(payload.toString()));

    assertPair(created, NAME, type, EDITOR);
    assertPair(get(type, idOf(created)), NAME, type, EDITOR);
  }

  @ParameterizedTest
  @EnumSource(value = CedarResourceType.class, names = {"TEMPLATE", "ELEMENT"})
  public void putFollowsARename(CedarResourceType type) throws IOException {
    ObjectNode payload = minimalPayload(type);
    payload.put(SCHEMA_ORG_NAME, "Before Rename 0.5.3");
    Response createResponse = request(collectionUrl(type)).post(Entity.json(payload.toString()));
    JsonNode created = created(type, createResponse);
    assertPair(created, "Before Rename 0.5.3", type, FIXTURE_EDITOR);

    ObjectNode renamed = created.deepCopy();
    renamed.put(SCHEMA_ORG_NAME, "After Rename 0.7.0");
    Response putResponse = request(itemUrl(type, idOf(created)))
        .header("If-Match", createResponse.getHeaderString("ETag"))
        .put(Entity.json(renamed.toString()));
    assertEquals(CedarResponseStatus.OK.getStatusCode(), putResponse.getStatus(),
        putResponse.readEntity(String.class));

    assertPair(get(type, idOf(created)), "After Rename 0.7.0", type, FIXTURE_EDITOR);
  }

  @Test
  public void unsignedJsonAndYamlWritesStoreTheSameWords() throws IOException {
    String name = "Same Words Either Way";
    ObjectNode payload = minimalPayload(TEMPLATE);
    payload.put(SCHEMA_ORG_NAME, name);
    payload.remove(JSON_SCHEMA_DESCRIPTION);

    JsonNode fromJson = create(TEMPLATE, Entity.json(payload.toString()));
    JsonNode fromYaml = create(TEMPLATE, Entity.entity("type: template\nname: " + name + "\n", APPLICATION_YAML));

    assertEquals(fromYaml.get(JSON_SCHEMA_TITLE).asText(), fromJson.get(JSON_SCHEMA_TITLE).asText());
    assertEquals(fromYaml.get(JSON_SCHEMA_DESCRIPTION).asText(), fromJson.get(JSON_SCHEMA_DESCRIPTION).asText());
    assertPair(fromJson, name, TEMPLATE, LIBRARY);
  }

  @Test
  public void nestedChildrenFollowTheirOwnNames() throws IOException {
    String yaml = """
        type: template
        name: Nested Parent
        children:
          - key: address
            type: element
            name: Address
            children:
              - key: street
                type: text-field
                name: Street
              - key: tags
                type: text-field
                name: Tag
                configuration:
                  multiple: true
        """;
    Response createResponse = request(collectionUrl(TEMPLATE)).post(Entity.entity(yaml, APPLICATION_YAML));
    JsonNode created = created(TEMPLATE, createResponse);
    String id = idOf(created);

    ObjectNode edited = created.deepCopy();
    ObjectNode address = objectAt(edited, "/properties/address");
    address.put(SCHEMA_ORG_NAME, "Postal Address");
    objectAt(address, "/properties/street").put(SCHEMA_ORG_NAME, "Street Line");
    objectAt(address, "/properties/tags/items").put(SCHEMA_ORG_NAME, "Keyword");
    Response putResponse = request(itemUrl(TEMPLATE, id))
        .header("If-Match", createResponse.getHeaderString("ETag"))
        .put(Entity.json(edited.toString()));
    assertEquals(CedarResponseStatus.OK.getStatusCode(), putResponse.getStatus(),
        putResponse.readEntity(String.class));

    JsonNode stored = get(TEMPLATE, id);
    assertPair(stored, "Nested Parent", TEMPLATE, LIBRARY);
    assertPair(stored.at("/properties/address"), "Postal Address", ELEMENT, LIBRARY);
    assertPair(stored.at("/properties/address/properties/street"), "Street Line", FIELD, LIBRARY);
    JsonNode tags = stored.at("/properties/address/properties/tags");
    assertEquals("array", tags.path("type").asText(), tags.toString());
    assertPair(tags.get("items"), "Keyword", FIELD, LIBRARY);
    if (tags.has(JSON_SCHEMA_TITLE)) {
      assertEquals(tags.at("/items/title"), tags.get(JSON_SCHEMA_TITLE), "the wrapper repeats its child's title");
    }
  }

  private static void assertPair(JsonNode node, String name, CedarResourceType type, String attribution) {
    String word = switch (type) {
      case TEMPLATE -> "template";
      case ELEMENT -> "element";
      default -> "field";
    };
    assertEquals(name + " " + word + " schema", node.path(JSON_SCHEMA_TITLE).asText(), node.toString());
    assertEquals(name + " " + word + " schema " + attribution,
        node.path(JSON_SCHEMA_DESCRIPTION).asText(), node.toString());
  }

  private ObjectNode minimalPayload(CedarResourceType type) throws IOException {
    JsonNode fixture = getFileContentAsJson(type == TEMPLATE ? MINIMAL_TEMPLATE_NULL_ID : MINIMAL_ELEMENT_NULL_ID);
    assertTrue(fixture instanceof ObjectNode, fixture.toString());
    return (ObjectNode) fixture;
  }

  private JsonNode create(CedarResourceType type, Entity<String> body) throws IOException {
    return created(type, request(collectionUrl(type)).post(body));
  }

  private JsonNode created(CedarResourceType type, Response response) throws IOException {
    String body = response.readEntity(String.class);
    assertEquals(CedarResponseStatus.CREATED.getStatusCode(), response.getStatus(), body);
    JsonNode created = JsonMapper.MAPPER.readTree(body);
    createdResources.put(idOf(created), type);
    return created;
  }

  private JsonNode get(CedarResourceType type, String id) throws IOException {
    Response response = request(itemUrl(type, id)).get();
    String body = response.readEntity(String.class);
    assertEquals(CedarResponseStatus.OK.getStatusCode(), response.getStatus(), body);
    return JsonMapper.MAPPER.readTree(body);
  }

  private static String idOf(JsonNode artifact) {
    return artifact.path(LinkedData.ID).asText();
  }

  private static ObjectNode objectAt(JsonNode root, String pointer) {
    JsonNode node = root.at(pointer);
    assertTrue(node instanceof ObjectNode, pointer + " in " + root);
    return (ObjectNode) node;
  }

  private String collectionUrl(CedarResourceType type) {
    return baseTestUrl + "/" + type.getPrefix();
  }

  private String itemUrl(CedarResourceType type, String id) throws IOException {
    return getUrlWithId(baseTestUrl, type, id);
  }

  private Invocation.Builder request(String url) {
    return testClient.target(url).request().header(AUTHORIZATION, authHeaderTestUser1)
        .accept(MediaType.APPLICATION_JSON_TYPE);
  }
}
