package org.metadatacenter.cedar.artifact.resources;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.metadatacenter.model.CedarResourceType;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_DESCRIPTION;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_TITLE;
import static org.metadatacenter.model.ModelNodeNames.SCHEMA_ORG_NAME;

/**
 * The JSON Schema {@code title} and {@code description} of a schema artifact, made to follow its
 * {@code schema:name} on every write the server normalises.
 * <p>
 * A template, element or field is also a JSON Schema document, and the meta-schemas require both
 * keywords. Nothing reads them but a person looking at the document, and CEDAR has always generated
 * them from the name. Until now the Template Designer was the only thing that regenerated them, and
 * only while the artifact was open in it. A rename from the dashboard, or by any other client, rewrote
 * {@code schema:name} and left the pair describing the old name. The server owns the derivation now,
 * so the pair follows the name whichever door the write came through.
 * <p>
 * The title is derived outright, in the canonical form {@code "<name> <kind> schema"} the Java and
 * TypeScript YAML readers compose. The description is that title followed by an attribution, and the
 * attribution is the one thing a client keeps: every generator signs the document in its description,
 * {@code "generated by the CEDAR Template Editor 2.9.5"} say, and the audits read that signature to
 * tell which tool wrote a stored artifact. A description that carries no signature takes the artifact
 * library's, which is also what an artifact posted as YAML receives, so the two media types store the
 * same words for the same unsigned artifact.
 * <p>
 * Only the artifact's own pair is rewritten. An embedded element or field carries a pair of its own,
 * written by whatever generated that piece, which may not be the tool saving the parent; it is left as
 * sent. An artifact with no usable name keeps what it has, for validation to judge.
 */
public final class JsonSchemaTitleAndDescription {

  private static final String LIBRARY_ATTRIBUTION = "generated by the CEDAR Artifact Library";

  /** The signature a generator leaves at the end of a description, from its first word onward. */
  private static final Pattern SIGNATURE = Pattern.compile("\\bgenerated by\\b.*",
      Pattern.CASE_INSENSITIVE | Pattern.DOTALL);

  private JsonSchemaTitleAndDescription() {
  }

  /** Rewrites the pair on a template, element or field. An artifact of any other kind is left untouched. */
  static void derive(JsonNode artifact, CedarResourceType resourceType) {
    String kind = kindWord(resourceType);
    if (kind == null || !(artifact instanceof ObjectNode node)) {
      return;
    }
    JsonNode nameNode = node.get(SCHEMA_ORG_NAME);
    if (nameNode == null || !nameNode.isTextual() || nameNode.textValue().isBlank()) {
      return;
    }
    String name = nameNode.textValue();
    JsonNode previous = node.get(JSON_SCHEMA_DESCRIPTION);
    String previousDescription = previous != null && previous.isTextual() ? previous.textValue() : null;
    node.put(JSON_SCHEMA_TITLE, title(name, kind));
    node.put(JSON_SCHEMA_DESCRIPTION, description(name, kind, previousDescription));
  }

  public static String title(String name, CedarResourceType resourceType) {
    return title(name, kindWord(resourceType));
  }

  /** The description of an artifact whose previous description carried no signature. */
  public static String description(String name, CedarResourceType resourceType) {
    return description(name, kindWord(resourceType), null);
  }

  /** The description an artifact gets when it previously carried {@code previous}, which may be null. */
  public static String description(String name, CedarResourceType resourceType, String previous) {
    return description(name, kindWord(resourceType), previous);
  }

  private static String title(String name, String kind) {
    return name + " " + kind + " schema";
  }

  private static String description(String name, String kind, String previous) {
    return title(name, kind) + " " + attribution(previous);
  }

  private static String attribution(String previous) {
    if (previous != null) {
      Matcher signature = SIGNATURE.matcher(previous);
      if (signature.find()) {
        return signature.group().trim();
      }
    }
    return LIBRARY_ATTRIBUTION;
  }

  /**
   * The word the pair uses for the artifact's kind, or null for a kind that carries no pair. A static
   * field is a field here as everywhere else the resource types are concerned.
   */
  private static String kindWord(CedarResourceType resourceType) {
    if (resourceType == null) {
      return null;
    }
    return switch (resourceType) {
      case TEMPLATE -> "template";
      case ELEMENT -> "element";
      case FIELD -> "field";
      default -> null;
    };
  }
}
