package controllers;

import com.fasterxml.jackson.databind.JsonNode;
import org.metadatacenter.templates.TemplateServerNames;
import org.metadatacenter.templates.mongodb.TemplatesServiceMongoDB;
import org.metadatacenter.templates.service.TemplatesService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.Configuration;
import play.Play;
import play.libs.Json;
import play.mvc.Controller;
import play.mvc.Result;
import utils.JsonUtils;

import javax.management.InstanceNotFoundException;
import java.util.ArrayList;
import java.util.List;

public class TemplateServerController extends Controller
{
  private static Logger log = LoggerFactory.getLogger(TemplateServerController.class);

  public static final TemplatesService<String, JsonNode> templatesService;

  private static JsonUtils jsonUtils;

  static {
    Configuration config = Play.application().configuration();
    templatesService = new TemplatesServiceMongoDB(config.getString(TemplateServerNames.MONGODB_DATABASE_NAME),
      config.getString(TemplateServerNames.TEMPLATES_COLLECTION_NAME),
      config.getString(TemplateServerNames.TEMPLATE_ELEMENTS_COLLECTION_NAME),
      config.getString(TemplateServerNames.TEMPLATE_INSTANCES_COLLECTION_NAME));
    jsonUtils = new JsonUtils();
  }

  /* Templates */

  public static Result createTemplate()
  {
    log.info("Received create template request");

    try {
      JsonNode template = request().body().asJson();
      JsonNode createdTemplate = templatesService.createTemplateLinkedData(template);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplate = jsonUtils.removeField(createdTemplate, "_id");
      return ok(createdTemplate);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findTemplate(String templateId, boolean expanded, boolean validation)
  {
    log.info("Received findTemplate request with template ID "+ templateId);
    try {
      JsonNode template = templatesService.findTemplateByLinkedDataId(templateId, expanded, validation);
      if (template!=null) {
        // Remove autogenerated _id field to avoid exposing it
        template = jsonUtils.removeField(template, "_id");
        return ok(template);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findAllTemplates()
  {
    try {
      List<JsonNode> templates = templatesService.findAllTemplates();
      List<JsonNode> templates2 = new ArrayList<JsonNode>();
      for (JsonNode template : templates) {
        // Remove autogenerated _id field to avoid exposing it
        templates2.add(jsonUtils.removeField(template, "_id"));
      }
      return ok(Json.toJson(templates2));
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result updateTemplate(String templateId)
  {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplate = templatesService.updateTemplateByLinkedDataId(templateId, modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplate = jsonUtils.removeField(updatedTemplate, "_id");
      return ok(updatedTemplate);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result deleteTemplate(String templateId)
  {
    try {
      templatesService.deleteTemplateByLinkedDataId(templateId);
      return ok();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  /* Template Elements */

  public static Result createTemplateElement()
  {
    try {
      JsonNode templateElement = request().body().asJson();
      JsonNode createdTemplateElement = templatesService.createTemplateElementLinkedData(templateElement);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplateElement = jsonUtils.removeField(createdTemplateElement, "_id");
      return ok(createdTemplateElement);
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findAllTemplateElements()
  {
    try {
      List<JsonNode> templateElements = templatesService.findAllTemplateElements();
      List<JsonNode> templateElements2 = new ArrayList<JsonNode>();
      for (JsonNode templateElement : templateElements) {
        // Remove autogenerated _id field to avoid exposing it
        templateElements2.add(jsonUtils.removeField(templateElement, "_id"));
      }
      return ok(Json.toJson(templateElements2));
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findTemplateElement(String templateElementId, boolean expanded, boolean validation)
  {
    try {
      JsonNode templateElement = templatesService.findTemplateElementByLinkedDataId(templateElementId, expanded,
        validation);
      if (templateElement!=null) {
        // Remove autogenerated _id field to avoid exposing it
        templateElement = jsonUtils.removeField(templateElement, "_id");
        return ok(templateElement);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result updateTemplateElement(String templateElementId)
  {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplateElement = templatesService.updateTemplateElementByLinkedDataId(templateElementId,
        modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplateElement = jsonUtils.removeField(updatedTemplateElement, "_id");
      return ok(updatedTemplateElement);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result deleteTemplateElement(String templateElementId)
  {
    try {
      templatesService.deleteTemplateElementByLinkedDataId(templateElementId);
      return ok();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  /* Template Instances */

  public static Result createTemplateInstance()
  {
    try {
      JsonNode templateInstance = request().body().asJson();
      JsonNode createdTemplateInstance = templatesService.createTemplateInstanceLinkedData(templateInstance);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplateInstance = jsonUtils.removeField(createdTemplateInstance, "_id");
      return ok(createdTemplateInstance);
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findAllTemplateInstances()
  {
    try {
      List<JsonNode> templateInstances = templatesService.findAllTemplateInstances();
      List<JsonNode> templateInstances2 = new ArrayList<JsonNode>();
      for (JsonNode templateInstance : templateInstances) {
        // Remove autogenerated _id field to avoid exposing it
        templateInstances2.add(jsonUtils.removeField(templateInstance, "_id"));
      }
      return ok(Json.toJson(templateInstances2));
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findTemplateInstance(String templateInstanceId)
  {
    try {
      JsonNode templateInstance = templatesService.findTemplateInstanceByLinkedDataId(templateInstanceId);
      if (templateInstance!=null) {
        // Remove autogenerated _id field to avoid exposing it
        templateInstance = jsonUtils.removeField(templateInstance, "_id");
        return ok(templateInstance);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result updateTemplateInstance(String templateInstanceId)
  {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplateInstance = templatesService.updateTemplateInstanceByLinkedDataId(templateInstanceId,
        modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplateInstance = jsonUtils.removeField(updatedTemplateInstance, "_id");
      return ok(updatedTemplateInstance);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result deleteTemplateInstance(String templateInstanceId)
  {
    try {
      templatesService.deleteTemplateInstanceByLinkedDataId(templateInstanceId);
      return ok();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

}
