package controllers;

import com.fasterxml.jackson.databind.JsonNode;
import org.metadatacenter.server.Constants;
import org.metadatacenter.server.service.FieldNameInEx;
import org.metadatacenter.server.service.TemplateService;
import org.metadatacenter.util.JsonObjectUtils;
import org.metadatacenter.util.LinkHeaderUtil;
import org.metadatacenter.util.Utils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.libs.Json;
import play.mvc.Result;

import javax.management.InstanceNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.metadatacenter.server.Constants.FIELD_NAMES_SUMMARY_TEMPLATE;
import static org.metadatacenter.server.Constants.HTTP_HEADER_LINK;

public class TemplateServerController extends GenericElementServerController {
  private static Logger log = LoggerFactory.getLogger(TemplateServerController.class);

  private static TemplateService<String, JsonNode> templateService;
  protected static List<String> FIELD_NAMES_SUMMARY_LIST;

  static {
    FIELD_NAMES_SUMMARY_LIST = new ArrayList<>();
    FIELD_NAMES_SUMMARY_LIST.addAll(config.getStringList(FIELD_NAMES_SUMMARY_TEMPLATE));
  }

  public static void injectTemplateService(TemplateService<String, JsonNode> ts) {
    templateService = ts;
  }

  public static Result createTemplate() {
    log.info("Received create template request");

    try {
      JsonNode template = request().body().asJson();
      JsonNode createdTemplate = templateService.createTemplateLinkedData(template);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplate = JsonObjectUtils.removeField(createdTemplate, "_id");
      // Set Location header pointing to the newly created template
      String id = createdTemplate.get("@id").asText();
      String absoluteUrl = routes.TemplateServerController.findTemplate(id, false, false).absoluteURL(request());
      response().setHeader(Constants.HTTP_HEADER_LOCATION, absoluteUrl);
      // Return created response
      return created(createdTemplate);
    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result findTemplate(String templateId, boolean expanded, boolean validation) {
    log.info("Received findTemplate request with ID " + templateId);
    try {
      JsonNode template = templateService.findTemplateByLinkedDataId(templateId, expanded, validation);
      if (template != null) {
        // Remove autogenerated _id field to avoid exposing it
        template = JsonObjectUtils.removeField(template, "_id");
        return ok(template);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result findAllTemplates(Integer limit, Integer offset, boolean summary, String fieldNames) {
    try {
      limit = ensureLimit(limit);
      checkPagingParameters(limit, offset);
      List<String> fieldNameList = getAndCheckFieldNames(fieldNames, summary);
      Map<String, Object> r = new HashMap<>();
      List<JsonNode> templates = null;
      if (summary) {
        templates = templateService.findAllTemplates(limit, offset, FIELD_NAMES_SUMMARY_LIST, FieldNameInEx.INCLUDE);
      } else if (fieldNameList != null) {
        templates = templateService.findAllTemplates(limit, offset, fieldNameList, FieldNameInEx.INCLUDE);
      } else {
        templates = templateService.findAllTemplates(limit, offset, FIELD_NAMES_EXCLUSION_LIST, FieldNameInEx.EXCLUDE);
      }
      long total = templateService.count();
      response().setHeader(Constants.HTTP_CUSTOM_HEADER_TOTAL_COUNT, String.valueOf(total));
      checkPagingParametersAgainstTotal(offset, total);
      String absoluteUrl = routes.TemplateServerController.findAllTemplates(0, 0, false, null).absoluteURL(request());
      absoluteUrl = Utils.trimUrlParameters(absoluteUrl);
      String linkHeader = LinkHeaderUtil.getPagingLinkHeader(absoluteUrl, total, limit, offset);
      if (!linkHeader.isEmpty()) {
        response().setHeader(HTTP_HEADER_LINK, linkHeader);
      }
      return ok(Json.toJson(templates));
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result updateTemplate(String templateId) {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplate = templateService.updateTemplateByLinkedDataId(templateId, modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplate = JsonObjectUtils.removeField(updatedTemplate, "_id");
      return ok(updatedTemplate);
    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result deleteTemplate(String templateId) {
    try {
      templateService.deleteTemplateByLinkedDataId(templateId);
      return noContent();
    } catch (IllegalArgumentException e) {
      return badRequestWithError(e);
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

}
