package controllers;

import com.fasterxml.jackson.databind.JsonNode;
import org.metadatacenter.server.service.FieldNameInEx;
import org.metadatacenter.server.service.TemplateInstanceService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.libs.Json;
import play.mvc.Result;
import utils.JsonUtils;

import javax.management.InstanceNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TemplateInstanceServerController extends GenericElementServerController {
  private static Logger log = LoggerFactory.getLogger(TemplateInstanceServerController.class);

  private static TemplateInstanceService<String, JsonNode> templateInstanceService;
  protected static List<String> FIELD_NAMES_SUMMARY_LIST;

  static {
    FIELD_NAMES_SUMMARY_LIST = new ArrayList<String>();
    FIELD_NAMES_SUMMARY_LIST.add("@id");
    FIELD_NAMES_SUMMARY_LIST.add("info.template_description");
    FIELD_NAMES_SUMMARY_LIST.add("info.template_title");
    FIELD_NAMES_SUMMARY_LIST.add("info.creation_date");
  }

  public static void injectTemplateInstanceService(TemplateInstanceService<String, JsonNode> tis) {
    templateInstanceService = tis;
  }

  public static Result createTemplateInstance() {
    try {
      JsonNode templateInstance = request().body().asJson();
      JsonNode createdTemplateInstance = templateInstanceService.createTemplateInstanceLinkedData(templateInstance);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplateInstance = JsonUtils.removeField(createdTemplateInstance, "_id");
      // Set Location header pointing to the newly created instance
      String id = createdTemplateInstance.get("@id").asText();
      String absoluteUrl = routes.TemplateInstanceServerController.findTemplateInstance(id).absoluteURL(request());
      response().setHeader("Location", absoluteUrl);
      // Return created response
      return created(createdTemplateInstance);
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result findAllTemplateInstances(Integer limit, Integer offset, boolean summary) {
    try {
      Map<String, Object> r = new HashMap<>();
      List<JsonNode> instances = null;
      if (summary) {
        instances = templateInstanceService.findAllTemplateInstances(limit, offset, FIELD_NAMES_SUMMARY_LIST,
            FieldNameInEx.INCLUDE);
        response().setHeader("Cedar-Field-Names", Json.toJson(FIELD_NAMES_SUMMARY_LIST).toString());
      } else {
        instances = templateInstanceService.findAllTemplateInstances(limit, offset, FIELD_NAMES_EXCLUSION_LIST,
            FieldNameInEx.EXCLUDE);
      }
      long total = templateInstanceService.count();
      response().setHeader("Total-Count", String.valueOf(total));
      return ok(Json.toJson(instances));
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result findTemplateInstance(String templateInstanceId) {
    try {
      JsonNode templateInstance = templateInstanceService.findTemplateInstanceByLinkedDataId(templateInstanceId);
      if (templateInstance != null) {
        // Remove autogenerated _id field to avoid exposing it
        templateInstance = JsonUtils.removeField(templateInstance, "_id");
        return ok(templateInstance);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result updateTemplateInstance(String templateInstanceId) {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplateInstance = templateInstanceService.updateTemplateInstanceByLinkedDataId
          (templateInstanceId,
          modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplateInstance = JsonUtils.removeField(updatedTemplateInstance, "_id");
      return ok(updatedTemplateInstance);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

  public static Result deleteTemplateInstance(String templateInstanceId) {
    try {
      templateInstanceService.deleteTemplateInstanceByLinkedDataId(templateInstanceId);
      return noContent();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerErrorWithError(e);
    }
  }

}
