package controllers;

import com.fasterxml.jackson.databind.JsonNode;
import org.metadatacenter.server.service.FieldNameInEx;
import org.metadatacenter.server.service.TemplateElementService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import play.libs.Json;
import play.mvc.Controller;
import play.mvc.Result;
import utils.JsonUtils;
import utils.ServiceResponseObject;

import javax.management.InstanceNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TemplateElementServerController extends GenericElementServerController {
  private static Logger log = LoggerFactory.getLogger(TemplateElementServerController.class);

  private static TemplateElementService<String, JsonNode> templateElementService;
  protected static List<String> FIELD_NAMES_SUMMARY_LIST;

  static {
    FIELD_NAMES_SUMMARY_LIST = new ArrayList<String>();
    FIELD_NAMES_SUMMARY_LIST.add("@id");
    FIELD_NAMES_SUMMARY_LIST.add("title");
    FIELD_NAMES_SUMMARY_LIST.add("properties.info.title");
    FIELD_NAMES_SUMMARY_LIST.add("properties.info.description");
  }

  public static void injectTemplateElementService(TemplateElementService<String, JsonNode> tes) {
    templateElementService = tes;
  }

  public static Result createTemplateElement() {
    try {
      JsonNode templateElement = request().body().asJson();
      JsonNode createdTemplateElement = templateElementService.createTemplateElementLinkedData(templateElement);
      // Remove autogenerated _id field to avoid exposing it
      createdTemplateElement = JsonUtils.removeField(createdTemplateElement, "_id");
      return ok(createdTemplateElement);
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findAllTemplateElements(Integer count, Integer page, boolean summary) {
    try {
      Map<String, Object> r = new HashMap<>();
      List<JsonNode> templates = null;
      ServiceResponseObject serviceResponseObject = ServiceResponseObject.build();
      if (summary) {
        templates = templateElementService.findAllTemplateElements(count, page, FIELD_NAMES_SUMMARY_LIST, FieldNameInEx.INCLUDE);
        serviceResponseObject.extra("fieldNames", FIELD_NAMES_SUMMARY_LIST);
      } else {
        templates = templateElementService.findAllTemplateElements(count, page, FIELD_NAMES_EXCLUSION_LIST, FieldNameInEx.EXCLUDE);
      }
      long total = templateElementService.count();
      serviceResponseObject.request("count", count)
          .request("page", page)
          .request("summary", summary)
          .response("total", total)
          .response("count", templates.size())
          .data(templates);
      return ok(Json.toJson(serviceResponseObject.get()));
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result findTemplateElement(String templateElementId, boolean expanded, boolean validation) {
    try {
      JsonNode templateElement = templateElementService.findTemplateElementByLinkedDataId(templateElementId, expanded,
          validation);
      if (templateElement != null) {
        // Remove autogenerated _id field to avoid exposing it
        templateElement = JsonUtils.removeField(templateElement, "_id");
        return ok(templateElement);
      }
      return notFound();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result updateTemplateElement(String templateElementId) {
    JsonNode modifications = request().body().asJson();
    try {
      JsonNode updatedTemplateElement = templateElementService.updateTemplateElementByLinkedDataId(templateElementId,
          modifications);
      // Remove autogenerated _id field to avoid exposing it
      updatedTemplateElement = JsonUtils.removeField(updatedTemplateElement, "_id");
      return ok(updatedTemplateElement);
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

  public static Result deleteTemplateElement(String templateElementId) {
    try {
      templateElementService.deleteTemplateElementByLinkedDataId(templateElementId);
      return ok();
    } catch (IllegalArgumentException e) {
      return badRequest();
    } catch (InstanceNotFoundException e) {
      return notFound();
    } catch (Exception e) {
      return internalServerError();
    }
  }

}
