package org.metadatacenter.cedar.artifact.resources;

import com.fasterxml.jackson.databind.JsonNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.EnumSource;
import org.metadatacenter.model.CedarResourceType;
import org.metadatacenter.util.json.JsonMapper;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_DESCRIPTION;
import static org.metadatacenter.model.ModelNodeNames.JSON_SCHEMA_TITLE;

/**
 * The pair follows schema:name at every level of a schema artifact. The title is the canonical one, and the
 * description keeps the signature of whatever generated the document.
 */
public class JsonSchemaTitleAndDescriptionTest {

  private static final String NAME = "NIAID Blueprint Compliant Schema 0.7.0";
  private static final String STALE_TITLE = "Niaid blueprint compliant schema 0.5.3 template schema";

  @Test
  public void theRootPairFollowsTheNameAndKeepsItsCaseAndItsSignature() throws Exception {
    JsonNode template = JsonMapper.MAPPER.readTree("""
        {"@type": "https://schema.metadatacenter.org/core/Template",
         "schema:name": "%s",
         "title": "%s",
         "description": "%s generated by the CEDAR Template Editor 2.9.5"}
        """.formatted(NAME, STALE_TITLE, STALE_TITLE));

    JsonSchemaTitleAndDescription.derive(template, CedarResourceType.TEMPLATE);

    assertEquals(NAME + " template schema", template.get(JSON_SCHEMA_TITLE).asText());
    assertEquals(NAME + " template schema generated by the CEDAR Template Editor 2.9.5",
        template.get(JSON_SCHEMA_DESCRIPTION).asText());
  }

  @Test
  public void aDescriptionWithoutASignatureTakesTheLibrarys() throws Exception {
    JsonNode template = JsonMapper.MAPPER.readTree(
        "{\"schema:name\": \"Study\", \"description\": \"Whatever an author once typed here\"}");

    JsonSchemaTitleAndDescription.derive(template, CedarResourceType.TEMPLATE);

    assertEquals("Study template schema generated by the CEDAR Artifact Library",
        template.get(JSON_SCHEMA_DESCRIPTION).asText());
    assertEquals(JsonSchemaTitleAndDescription.description("Study", CedarResourceType.TEMPLATE),
        template.get(JSON_SCHEMA_DESCRIPTION).asText());
    assertEquals("Study template schema generated by the CEDAR Template Editor 2.9.5",
        JsonSchemaTitleAndDescription.description("Study", CedarResourceType.TEMPLATE,
            "Old template schema generated by the CEDAR Template Editor 2.9.5"));
  }

  @ParameterizedTest
  @EnumSource(value = CedarResourceType.class, names = {"TEMPLATE", "ELEMENT", "FIELD"})
  public void eachKindHasItsOwnWord(CedarResourceType type) throws Exception {
    JsonNode artifact = JsonMapper.MAPPER.readTree("{\"schema:name\": \"Study\"}");

    JsonSchemaTitleAndDescription.derive(artifact, type);

    String word = switch (type) {
      case TEMPLATE -> "template";
      case ELEMENT -> "element";
      default -> "field";
    };
    assertEquals("Study " + word + " schema", artifact.get(JSON_SCHEMA_TITLE).asText());
    assertEquals(JsonSchemaTitleAndDescription.title("Study", type), artifact.get(JSON_SCHEMA_TITLE).asText());
    assertEquals(JsonSchemaTitleAndDescription.description("Study", type),
        artifact.get(JSON_SCHEMA_DESCRIPTION).asText());
  }

  @Test
  public void aPairIsAddedWhereTheClientSentNone() throws Exception {
    JsonNode field = JsonMapper.MAPPER.readTree("{\"schema:name\": \"Disease\"}");

    JsonSchemaTitleAndDescription.derive(field, CedarResourceType.FIELD);

    assertEquals("Disease field schema", field.get(JSON_SCHEMA_TITLE).asText());
    assertTrue(field.has(JSON_SCHEMA_DESCRIPTION));
  }

  @Test
  public void aNodeWithoutAUsableNameKeepsWhatItHas() throws Exception {
    JsonNode missing = JsonMapper.MAPPER.readTree("{\"title\": \"Kept\"}");
    JsonNode blank = JsonMapper.MAPPER.readTree("{\"schema:name\": \"  \", \"title\": \"Kept\"}");
    JsonNode notText = JsonMapper.MAPPER.readTree("{\"schema:name\": 7, \"title\": \"Kept\"}");

    for (JsonNode node : new JsonNode[]{missing, blank, notText}) {
      JsonSchemaTitleAndDescription.derive(node, CedarResourceType.TEMPLATE);
      assertEquals("Kept", node.get(JSON_SCHEMA_TITLE).asText(), node.toString());
      assertFalse(node.has(JSON_SCHEMA_DESCRIPTION), node.toString());
    }
  }

  @Test
  public void anInstanceIsLeftAlone() throws Exception {
    JsonNode instance = JsonMapper.MAPPER.readTree("{\"schema:name\": \"Study metadata\", \"title\": \"Kept\"}");

    JsonSchemaTitleAndDescription.derive(instance, CedarResourceType.INSTANCE);

    assertEquals("Kept", instance.get(JSON_SCHEMA_TITLE).asText());
    assertFalse(instance.has(JSON_SCHEMA_DESCRIPTION));
  }

  @Test
  public void embeddedChildrenAreLeftAsSent() throws Exception {
    JsonNode template = JsonMapper.MAPPER.readTree("""
        {"@type": "https://schema.metadatacenter.org/core/Template",
         "schema:name": "Parent",
         "properties": {
           "address": {
             "type": "object",
             "@type": "https://schema.metadatacenter.org/core/TemplateElement",
             "schema:name": "Postal Address",
             "title": "Address element schema",
             "description": "Address element schema generated by the CEDAR Template Editor 2.6.19",
             "properties": {
               "street": {
                 "type": "object",
                 "@type": "https://schema.metadatacenter.org/core/TemplateField",
                 "schema:name": "Street Line",
                 "title": "'Street' field schema",
                 "description": "'Street' field schema auto-generated by CEDAR"
               }
             }
           },
           "tags": {
             "type": "array",
             "title": "Tag field schema",
             "items": {
               "@type": "https://schema.metadatacenter.org/core/TemplateField",
               "schema:name": "Keyword",
               "title": "Tag field schema"
             }
           }
         }}
        """);
    JsonNode childrenBefore = template.get("properties").deepCopy();

    JsonSchemaTitleAndDescription.derive(template, CedarResourceType.TEMPLATE);

    assertEquals("Parent template schema", template.at("/title").asText());
    assertEquals(childrenBefore, template.get("properties"),
        "a child's pair was written by whatever generated that piece, and stays as sent");
  }
}
